spring.application.name=fileIo

# データベースの設定
spring.datasource.driver-class-name=org.postgresql.Driver
# local内での接続用URL
spring.datasource.url=jdbc:postgresql://localhost:5432/MoneyTrack
spring.datasource.username=postgres
spring.datasource.password=postgresql

mybatis.configuration.default-map-type=java.util.LinkedHashMap

# AWS S3の設定
# リージョン
aws.region=
# S3バケット名
aws.s3.bucketName=
# S3内のルートディレクトリ
aws.s3.rootKey=
# AWS認証情報
aws.accessKey=
# AWS秘密鍵
aws.secretKey=